// levels/LNN.txt + LNN.plan.json + meta.json  ->  src/20_levels.js
const fs = require('fs'), { check } = require('./check');
const R = __dirname + '/../';
const meta = JSON.parse(fs.readFileSync(R + 'levels/meta.json', 'utf8'));
const out = [];
let missing = 0;
for (let i = 0; i < meta.length; i++) {
  const id = 'L' + String(i + 1).padStart(2, '0');
  const mf = R + 'levels/' + id + '.txt', pf = R + 'levels/' + id + '.plan.json';
  if (!fs.existsSync(mf)) { console.log(id + ': MISSING map'); missing++; continue }
  const map = fs.readFileSync(mf, 'utf8').replace(/\n+$/, '');
  let par = 1;
  if (fs.existsSync(pf)) {
    try {
      const r = check(map, JSON.parse(fs.readFileSync(pf, 'utf8')));
      if (r.ok) par = r.loops; else { console.log(id + ': plan does NOT solve'); missing++ }
    } catch (e) { console.log(id + ': plan error ' + e.message); missing++ }
  } else { console.log(id + ': no plan'); missing++ }
  out.push('{n:' + JSON.stringify(meta[i].n) + ',t:' + JSON.stringify(meta[i].t) +
    ',p:' + par + ',m:\n`' + map.replace(/\\/g, '\\\\') + '`}');
}
const src = '// ================= LEVELS =================\n' +
  '// generated by test/gen.js from levels/*.txt - edit those, not this\n' +
  'var LEV = [\n' + out.join(',\n\n') + '\n];\n';
fs.writeFileSync(R + 'src/20_levels.js', src);
console.log('\nwrote ' + out.length + ' levels to src/20_levels.js' + (missing ? '  (' + missing + ' problems)' : ''));
